### ISSUE TITLE
Erreur récupération données

### ISSUE THREAD

**Issue by max5962** [beufanet/gazpar#2]
Bonjour,
J'ai un problème depuis quelques jours.
J'arrive à me connecter mais j'ai ça :

```
2020-06-11 13:26:12,596 get Data from GRDF from 08/06/2020 to 11/06/2020
Traceback (most recent call last):
  File "/config/gazpart/gazpar/gazinflux.py", line 143, in <module>
    t = datetime.datetime.strptime(d['date'] + " 12:00", '%d-%m-%Y %H:%M')
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '0 12:00' does not match format '%d-%m-%Y %H:%M
```'

**Comment by beufanet** [comment]
Possible de m'envoyer en debug le json renvoyé par GRDF ?

**Comment by beufanet** [comment]
No update
