### ISSUE TITLE
   (data_string, format)) ValueError: time data '0 12:00' does not match format

### ISSUE THREAD

**Issue by philuxe** [beufanet/gazpar#6]
depuis qq jours la récup des données ne fonctionne plus:

2021-01-25 13:16:35,504 logging in InfluxDB Server Host 192.168.1.87...
2021-01-25 13:16:35,505 logged in InfluxDB Server Host 192.168.1.87 succesfully
2021-01-25 13:16:35,505 logging in GRDF URI https://monespace.grdf.fr/monespace/particulier...
2021-01-25 13:16:38,794 logged in successfully!
2021-01-25 13:16:38,794 looking for last value date on InfluxDB 'conzo_gaz' on host 192.168.1.87...
2021-01-25 13:16:38,809 found last fetch date 18/01/2021 on InfluxDB 'conzo_gaz' on host 192.168.1.87...
2021-01-25 13:16:38,809 will use 1610967600.0 as firstDate and 18/01/2021 as startDate
2021-01-25 13:16:41,967 get Data from GRDF from 18/01/2021 to 25/01/2021
Traceback (most recent call last):
  File "/home/aaa/SCRIPTS/beufanet-gazpar/gazinflux.py", line 201, in <module>
    main()
  File "/home/aaa/SCRIPTS/beufanet-gazpar/gazinflux.py", line 149, in main
    t = datetime.datetime.strptime(d['date'] + " 12:00", '%d-%m-%Y %H:%M')
  File "/usr/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '0 12:00' does not match format '%d-%m-%Y %H:%M'

**Comment by beufanet** [comment]
Malheureusement il semble que le site de grdf soit un peu en carafe ces derniers temps. Mon script ne peut pas fixer les problèmes du site. 
Je surveille si ca remarche, mais en l'état, aucune idée de ce qu'il se passe chez eux ces derniers temps...

**Comment by beufanet** [comment]
Ca fonctionne de nouveau ce soir. Merci d'attendre au moins une semaine lorsque cela ne fonctionne pas. Je devrais ajouter des codes d'erreurs mais vu le nombre d'erreurs sur le site .... :D

**Comment by lezohtml** [comment]
Hello, 
Le problème est de nouveau présent. 
J'imagine que GRDF a mis à jour son site.
